// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnyzjtsbflejdiyztprh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRueXpqdHNiZmxlamRpeXp0cHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODE2MzcsImV4cCI6MjA2MTE1NzYzN30.dP2XK86NOGYmZglrlHkCrv0Cydb3GBgHlULSXfx8y1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);